import os
import string

l=os.listdir("./")

def isSourceFile(f):
	return (string.find(f,".c")>=0 or string.find(f,".h")>=0) and not string.find(f,"~")>=0 and string.find(f,"main.c")<0


def getAllSourceFiles(dir):
	l=os.listdir(dir)
	return filter(isSourceFile,l)


libsrc=getAllSourceFiles("./")

print "Source files:"
print libsrc
print ""


Library('lincity_oldgui',libsrc,CCFLAGS="-Igui_interface -I. -I.. -Ilincity -DHAVE_CONFIG_H")
Program('lincity_oldgui',['main.cc'],CCFLAGS="-Igui_interface -I. -I.. -Ilincity -DHAVE_CONFIG_H",LIBS=['SDL','lincity_oldgui','lincity','lincity_modules','lincity','lincity_oldgui','png'],LIBPATH=['.','../lincity','../lincity/modules'])

