<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns="http://lincity-ng.berlios.de/gui"
	version="1.0">

	<xsl:output method="xml" version="1.0" encoding="UTF-8" indent="yes"/>

	<xsl:template match="/">
		<xsl:comment>
WARNING: This file is automatically generated. Do not edit!
</xsl:comment>
		<xsl:copy-of select="."/>
	</xsl:template>
</xsl:stylesheet>
