<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns="http://lincity-ng.berlios.de/gui"
  version="1.0"
>

<xsl:output method="xml" version="1.0" encoding="UTF-8" indent="no"/>
<xsl:strip-space elements="*"/>

<xsl:template match="/">
  <xsl:comment>WARNING: This file is automatically generated. Do not edit!</xsl:comment>
  <xsl:apply-templates select="." mode="copying"/>
</xsl:template>

<xsl:template match="//if-NLS" mode="copying">
  <xsl:if test="@value = $NLS">
    <xsl:apply-templates select="node()" mode="copying"/>
  </xsl:if>
</xsl:template>

<xsl:template match="node()|@*" mode="copying">
  <xsl:copy>
    <xsl:apply-templates select="node()|@*" mode="copying"/>
  </xsl:copy>
</xsl:template>
</xsl:stylesheet>
