Import('*')

source = Glob("*.cpp")
cpppath = env['CPPPATH'] + ["#/src/lincity", "#/src/gui_interface"]
libs = env['LIBS'] + ["lincity"]
app = env.Program(target = "lincity_oldgui", source = source,
        CPPPATH = cpppath, LIBS = libs)
AddPostAction(app, "ln -sf $TARGET .")
Default(app)

